# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
q3 = np.arange(10, 50)

4. Find the shape of previous array in question 3

In [6]:
q3.shape

(40,)

5. Print the type of the previous array in question 3

In [7]:
type(q3)

numpy.ndarray

6. Print the numpy version and the configuration


In [14]:
print(np.__version__)
print()
np.show_config()

1.18.5

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Awais/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Awais/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Awais/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl

7. Print the dimension of the array in question 3


In [12]:
q3.ndim

1

8. Create a boolean array with all the True values

In [32]:
x = np.array([True, True, False, False], dtype=bool)
y = np.array([2, 55, 0, 0, 6], dtype=bool)
y

array([ True,  True, False, False,  True])

9. Create a two dimensional array



In [33]:
np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [34]:
np.empty((2, 3, 5))

array([[[ 8.20340414e-312,  9.78249979e-322,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 5.02034658e+175,  4.51681840e-037,  5.40524961e-066,
          1.21480363e-046,  9.59433331e-043],
        [ 7.26113039e-043,  3.59751658e+252,  8.93185432e+271,
          4.76484771e+180,  1.47763641e+248]],

       [[ 1.16096346e-028,  7.69165785e+218,  1.35617292e+248,
          1.76913630e+160,  1.52431606e-052],
        [ 1.71736830e+185,  2.38393699e+180,  5.43386554e-143,
          1.16097020e-028,  6.37112413e-067],
        [ 9.72389950e-067,  1.90016070e-052,  1.11763122e+261,
          1.16318408e-028, -6.79764374e-310]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [35]:
q3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [36]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float32')

In [50]:
arr.dtype

dtype('float32')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [51]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [52]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [58]:
arr = np.arange(10)
print([x for x in arr if x%2 == 1])
arr[arr%2 == 1]

[1, 3, 5, 7, 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [60]:
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [61]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [63]:
arr = np.ones((4, 4))
print(arr)
arr[1:-1, 1:-1] = 0
arr

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [64]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [66]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [69]:
arr = np.arange(10).reshape(2, 5)
print(arr)
arr[0:1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [70]:
arr = np.arange(10).reshape(2, 5)
print(arr)
arr[1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [71]:
arr = np.arange(10).reshape(2, 5)
print(arr)
arr[:, 2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [73]:
arr = np.random.rand(10, 10)
print('max : {}'.format(arr.max()))
arr.min()

max : 0.9936244609361488


0.01401915477832949

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.unique(a&b)

array([0, 1, 2, 3, 4], dtype=int32)

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b, return_indices=True)[1])

[1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != 'Will']

array([[ 1.87724307,  0.24569247,  0.80575938,  0.81071621],
       [-1.97224931,  0.78926415, -0.3446298 , -0.72519724],
       [ 0.95585334, -1.06027434,  0.83190789,  0.72390503],
       [ 0.17670996, -0.21951648,  0.91221353,  0.43210573],
       [ 0.78285389, -0.41541494,  0.21874798, -0.29087141]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[(names != 'Will') & (names != 'Joe')]

array([[-0.30553354,  0.82537899,  0.43045202, -0.66386993],
       [ 0.08978023,  1.54410957, -0.45711661, -0.16202732]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [86]:
np.arange(1, 16, dtype='int32').reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [89]:
q32 = np.arange(1, 17, dtype='int32').reshape(2, 2, 4)
q32

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [91]:
q32.swapaxes(2, 1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [93]:
arr = np.random.rand(10)
arr[np.sqrt(arr) < 0.5] = 0
arr

array([0.        , 0.        , 0.70702435, 0.        , 0.74068423,
       0.61980556, 0.66823371, 0.41226327, 0.84682658, 0.52588322])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [95]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
np.maximum(arr1, arr2)

array([0.77167853, 0.69122939, 0.99040544, 0.66952469, 0.8453962 ,
       0.28907262, 0.14863093, 0.33113252, 0.75950823, 0.71365353,
       0.26397625, 0.51269888])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [97]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [32]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
mask = np.intersect1d(a, b)
a[a != mask]

array([1, 2, 3, 4])

In [36]:
np.delete(a, np.intersect1d(a, b, return_indices=True)[1])

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [100]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
print(sampleArray)
sampleArray[:, 1] = newColumn[0]
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [103]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [104]:
arr = np.random.rand(20)
arr.cumsum()

array([ 0.47592942,  0.67058406,  1.6576433 ,  2.28965456,  2.91089286,
        3.81501109,  4.73923802,  4.95537673,  5.50877547,  6.02424688,
        6.79803863,  7.17366927,  7.6082207 ,  8.06993497,  8.52329259,
        8.60590755,  9.29984714, 10.10697042, 10.81662683, 10.82716427])